Repository Lotte-CUTEam/Movie-Ticket-System, pull requests merged in 2022-07, with the labels that each got.

#15 [ Movie List ] 영화 DTO, DAO 생성 #6 #7
  .gitignore
  src/CREATE_TABLE.sql
  src/dao/MovieDao.java
  src/dto/MovieDto.java
  src/test/INSERT_TESTDATA.sql
  src/test/dao/MovieDaoTest.java
Labels: 🍭 feat, 🍀 test, 💻 chore

#19 feat : ReservationDto 작성 (#14)
  src/dto/ReservationDto.java
Labels: 🍭 feat

#20 Main Page 초안 추가
  WebContent/assets/css/font-awesome.css
  WebContent/assets/css/reset.css
  WebContent/assets/css/style.css
  WebContent/assets/css/swiper.css
  WebContent/assets/fonts/FontAwesome.otf
  WebContent/assets/fonts/fontawesome-webfont.eot
  WebContent/assets/fonts/fontawesome-webfont.svg
  WebContent/assets/fonts/fontawesome-webfont.ttf
  WebContent/assets/fonts/fontawesome-webfont.woff
  WebContent/assets/fonts/fontawesome-webfont.woff2
  WebContent/assets/img/Che_1920774.jpg
  WebContent/assets/img/Elv_1920774.jpg
  WebContent/assets/img/Thor_1920774.jpg
  WebContent/assets/img/close.svg
  WebContent/assets/img/cute-logo.png
  WebContent/assets/img/down.svg
  WebContent/assets/img/logo-footer.png
  WebContent/assets/img/logo.gif
  WebContent/assets/js/html5shiv.min.js
  WebContent/assets/js/ie-checker.js
  WebContent/assets/js/iframe_api.js
  WebContent/assets/js/jquery.min_1.12.4.js
  WebContent/assets/js/modernizr-custom.js
  WebContent/assets/js/movie.js
  WebContent/assets/js/slick.min.js
  WebContent/assets/js/swiper.min.js
  WebContent/main.jsp
Labels: 🍭 feat

#30 [ Movie List ] 영화 목록 Controller #6 #7 #8
  .gitignore
  src/controller/MovieController.java
  src/dao/MovieDao.java
  src/dto/MovieDto.java
  src/test/dao/MovieDaoTest.java
Labels: 🍭 feat, 👻 fix, 🍀 test, 💻 chore

#33 [MovieDetail] 영화 상세 페이지 구현 #12 #13
  .gitignore
  WebContent/movie/movieDetail.jsp
  src/controller/MovieController.java
  src/controller/MovieDetailController.java
  src/db/DBConnection.java
  src/dto/MovieDto.java
  src/test/dao/MovieDaoTest.java
Labels: 🍭 feat

#35 [ Fix ] DBConnection
  src/dao/MovieDao.java
  src/db/DBConnection.java
  src/test/dao/MovieDaoTest.java
Labels: 👻 fix, 🚨 hotfix

#37 Main Page DB 연동 및 Header&Footer 레이아웃
  WebContent/headerNfooter.jsp
  WebContent/main.jsp
Labels: 🍭 feat

#40 MainController 추가 및 Main Page 수정
  WebContent/assets/img/cute-logo.png
  WebContent/headerNfooter.jsp
  WebContent/main.jsp
  src/controller/MainController.java
Labels: 🍭 feat, 👻 fix

#42 로그인 및 회원가입, 메인페이지 수정
  WebContent/headerNfooter.jsp
  WebContent/main.jsp
  WebContent/member/js/login.js
  WebContent/member/login.jsp
  WebContent/member/logout.jsp
  WebContent/member/message.jsp
  src/controller/MemberController.java
  src/dao/MemberDao.java
Labels: 👻 fix

#45 feat: 영화 목록 페이징, 필터, 검색 기능 구현 및 CSR 적용 #7 #8 #9
  WebContent/assets/css/style_movieList.css
  WebContent/movie/movieList.jsp
  WebContent/movie/movieListTemplate.jsp
  src/controller/MovieController.java
  src/controller/MovieHomeController.java
  src/dao/MovieDao.java
  src/dto/AllMovieDto.java
  src/dto/MovieDto.java
  src/test/dao/MovieDaoTest.java
Labels: 🍭 feat, 🍑 refactor, 💻 chore

#47 영화 선택 화면 개발 및 컨트롤러 개발
  WebContent/assets/css/res_content.css
  WebContent/assets/css/res_default.css
  WebContent/assets/css/reservation.css
  WebContent/assets/img/cute-logo-small.png
  WebContent/reservation/reservation.js
  WebContent/reservation/reservation.jsp
  src/enums/Location.java
Labels: 🍭 feat

#48 chore: dev 브랜치 합치기
  WebContent/WEB-INF/lib/gson-2.2.2.jar
  WebContent/WEB-INF/lib/json-lib-2.4-jdk15.jar
  WebContent/WEB-INF/lib/json-simple-1.1.1.jar
  WebContent/assets/css/res_content.css
  WebContent/assets/css/res_default.css
  WebContent/assets/css/reservation.css
  WebContent/assets/css/style_movieList.css
  WebContent/assets/img/cute-logo-small.png
  WebContent/assets/img/cute-logo.png
  WebContent/headerNfooter.jsp
  WebContent/main.jsp
  WebContent/member/js/login.js
  WebContent/member/login.jsp
  WebContent/member/logout.jsp
  WebContent/member/message.jsp
  WebContent/movie/movieList.jsp
  WebContent/movie/movieListTemplate.jsp
  WebContent/reservation/reservation.js
  WebContent/reservation/reservation.jsp
  src/controller/MainController.java
  src/controller/MemberController.java
  src/controller/MovieController.java
  src/controller/MovieHomeController.java
  src/dao/MemberDao.java
  src/dao/MovieDao.java
  src/dto/AllMovieDto.java
  src/dto/MovieDto.java
  src/enums/Location.java
  src/test/dao/MovieDaoTest.java
Labels: 💻 chore

#50 fix: Movie List 수정
  WebContent/movie/movieList.jsp
  src/controller/MovieController.java
  src/controller/MovieHomeController.java
  src/dao/MovieDao.java
Labels: 👻 fix

#51 feat: header & footer 추가
  WebContent/footer.jsp
  WebContent/header.jsp
  WebContent/headerNfooter.jsp
  WebContent/main.jsp
Labels: 🍭 feat, 👻 fix

#55 feat: header&footer css 분리
  WebContent/assets/css/reset_hnf.css
  WebContent/assets/css/style_hnf.css
  WebContent/footer.jsp
  WebContent/header.jsp
Labels: 🍭 feat

#63 각 페이지 title 수정, 영화 페이지 퀵바 추가
  WebContent/main.jsp
  WebContent/member/login.jsp
  WebContent/member/regi.jsp
  WebContent/movie/movieDetail.jsp
  WebContent/movie/movieList.jsp
  WebContent/mypage/myPage.jsp
  WebContent/mypage/reservationDetail.jsp
  WebContent/quickbar.jsp
  WebContent/reservation/reservationDetail.jsp
Labels: 🍭 feat

#68 fix: 검색, 페이지 기능 수정
  WebContent/movie/js/movie.js
  src/controller/MovieController.java
  src/dao/MovieDao.java
Labels: 👻 fix, 🚨 hotfix

#69 Footer 기능 추가, MainPage 수정, MoviePage css 수정
  WebContent/footer.jsp
  WebContent/main.jsp
  WebContent/movie/movieDetail.jsp
Labels: 🍭 feat, 👻 fix

#71 fix: Movie Detail 페이지 css 재수정
  WebContent/movie/movieDetail.jsp
Labels: 👻 fix

#73 fix: Main Page 버튼 경로 수정
  WebContent/main.jsp
Labels: 👻 fix

#83 fix: 영화 예매
  WebContent/reservation/reservation.js
  WebContent/reservation/reservation.jsp
  WebContent/reservation/reservationDetail.jsp
  src/controller/ReservationController.java
  src/controller/ScreenController.java
  src/dao/ScreenDao.java
Labels: 👻 fix, 🛠 style, 🚨 hotfix
